name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-jammy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install playground dependencies
        run: cd playground && npm ci

      - name: Start dev server
        run: |
          cd playground && npm run dev &
          echo "Waiting for dev server to be ready..."
          for i in {1..30}; do
            if curl -f http://localhost:8000 > /dev/null 2>&1; then
              echo "Dev server is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
        env:
          CI: true

      - name: Run Playwright tests
        run: npm run test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
